version: "3"
services:
  mlflow-backend-store:
    platform: linux/amd64
    image: postgres:14.0
    container_name: mlflow-backend-store
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-U",
          "${POSTGRES_USER}",
          "-d",
          "${POSTGRES_DB}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  mlflow-artifact-store:
    platform: linux/amd64
    image: minio/minio
    container_name: mlflow-artifact-store
    ports:
      - ${MINIO_PORT_INTERNAL}:${MINIO_PORT_INTERNAL}
      - ${MINIO_PORT_EXTERNAL}:${MINIO_PORT_EXTERNAL}
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    command: server /data/minio --console-address :${MINIO_PORT_EXTERNAL}
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:${MINIO_PORT_INTERNAL}/minio/health/live",
        ]
      interval: 30s
      timeout: 20s
      retries: 3

  mlflow-server:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ${DOCKERFILE_NAME}
    container_name: mlflow-server
    depends_on:
      mlflow-backend-store:
        condition: service_healthy
      mlflow-artifact-store:
        condition: service_healthy
    ports:
      - ${MLFLOW_PORT_INTERNAL}:${MLFLOW_PORT_EXTERNAL}
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      MLFLOW_S3_ENDPOINT_URL: http://mlflow-artifact-store:${MINIO_PORT_INTERNAL}
    command:
      - /bin/sh
      - -c
      - |
        mc config host add mlflowminio http://mlflow-artifact-store:${MINIO_PORT_INTERNAL} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
        mc mb --ignore-existing mlflowminio/mlflow
        mlflow server \
        --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@mlflow-backend-store/${POSTGRES_DB} \
        --default-artifact-root s3://mlflow/ \
        --host ${MLFLOW_SERVER_HOST}
